server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sg_security?serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      max-total: 20
      max-idle: 5
      max-wait-millis: 8000
  redis:
    port: 6379
    host: 192.168.10.100
    lettuce:
      pool:
        max-idle: 5
        min-idle: 0
        max-active: 20
        max-wait: 5000
    connect-timeout: 5000
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true