server:
  port: 8888
  servlet:
    context-path: /api
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
car:
  brand: 长安
  price: 100000
path:
  file: D:\upload\
  domain: http://localhost:8888/api/
